import Index from "views/Index.js";
import Profile from "views/examples/Profile.js";
import Register from "views/examples/Register.js";
import Login from "views/examples/Login.js";

var routes = [
  {
    path: "/dashboard",
    name: "Dashboard",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/admin",
  },
  {
    path: "/user-management",
    name: "User Management",
    icon: "ni ni-single-02 text-orange",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/broker-management",
    name: "Broker Management",
    icon: "ni ni-single-02 text-orange",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/usdt-wallet-management",
    name: "USDT Wallet Management",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/payment-integrations",
    name: "Payment Integrations",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/transactions",
    name: "Transactions",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/commissions-management",
    name: "Commissions Management",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/load-balancing Configuration",
    name: "Load-Balancing Configuration",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/api-management",
    name: "Api Management",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/notification-center",
    name: "Notification Center",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/System Reports",
    name: "System Reports",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/audit-logs",
    name: "Audit Logs",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/admin",
  },
  {
    path: "/dashboard",
    name: "Dashboard",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/broker",
  },
  {
    path: "/user-management",
    name: "User Management",
    icon: "ni ni-single-02 text-orange",
    component: <Profile />,
    layout: "/broker",
  },
  {
    path: "/transactions-management",
    name: "Transactions Management",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/broker",
  },
  {
    path: "/commission-overview",
    name: "Commission Overview",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/broker",
  },
  {
    path: "/notification-center",
    name: "Notification Center",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/broker",
  },
  {
    path: "/System Reports",
    name: "System Reports",
    icon: "ni ni-single-02 text-pink",
    component: <Profile />,
    layout: "/broker",
  },

  {
    path: "/dashboard",
    name: "Dashboard",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/client",
  },

  {
    path: "/transactions",
    name: "Transactions",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/client",
  },
  {
    path: "/pay-in",
    name: "PayIn",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/client",
  },
  {
    path: "/pay-out",
    name: "PayOut",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/client",
  },
  {
    path: "/notifications",
    name: "Notifications",
    icon: "ni ni-tv-2 text-primary",
    component: <Index />,
    layout: "/client",
  },
  {
    path: "/login",
    name: "Login",
    icon: "ni ni-key-25 text-info",
    component: <Login />,
    layout: "/auth",
  },
  {
    path: "/register",
    name: "Register",
    icon: "ni ni-circle-08 text-pink",
    component: <Register />,
    layout: "/auth",
  },
];
export default routes;
